### ISSUE TITLE
Fails to install with 404 08/12/2024

### ISSUE THREAD

**Issue by n-a-b-s-t-e-r** [zavocc/debdroid#2]
Fails to install debian stable or bookworm on Poco X3 Pro phone. Reports 404 not found.

**Comment by zavocc** [comment]
Will look into it... I'll tag you once a root cause has been found

**Comment by thesaguaro** [comment]
same problem

**Comment by zavocc** [comment]
Will roll out a fix next week, problem has been found

**Comment by zavocc** [comment]
Will roll out a fix next week, problem has been found

**Comment by zavocc** [comment]
![Screenshot_2024-12-23-07-44-57-29_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/user-attachments/assets/4261f617-21d7-4287-8c76-027fdbaaf6e1)

Will push the fix in the coming days

**Comment by n-a-b-s-t-e-r** [comment]
I have since discovered 'proot-distro install debian', and am interested to know the difference with Debdroid?

Thanks for responding and making a fix :-)

*From: *Wyatt Marcus Bautista ***@***.***>
*To: *zavocc/debdroid ***@***.***>
*CC: *n-a-b-s-t-e-r ***@***.***>; Author ***@***.***>
*Date: *23 Dec 2024 05:15:53
*Subject: *Re: [zavocc/debdroid] Fails to install with 404 08/12/2024 (Issue #2)

**Comment by zavocc** [comment]
Its now fixed

> I have since discovered 'proot-distro install debian', and am interested to know the difference with Debdroid?

The difference is it sets up fundamental things like user account and sudo access for you, as well as preinstalled packages.
Planning to add more features soon such as one-command desktop installation, it contains the same set of features with proot-distro such as ability to run termux commands in debian, fixes, and more
